// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"
)

type Querier interface {
	CreateAuthenticationToken(ctx context.Context, arg CreateAuthenticationTokenParams) (AuthenticationToken, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAuthenticationToken(ctx context.Context, userID int64) error
	GetAllUsers(ctx context.Context) ([]User, error)
	GetAuthenticationTokenByAccessToken(ctx context.Context, accessToken string) (AuthenticationToken, error)
	GetRoles(ctx context.Context) ([]Role, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
}

var _ Querier = (*Queries)(nil)
