// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.2
// source: user_event_service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserEventsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UserEventsRequest) Reset() {
	*x = UserEventsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_event_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserEventsRequest) ProtoMessage() {}

func (x *UserEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_event_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserEventsRequest.ProtoReflect.Descriptor instead.
func (*UserEventsRequest) Descriptor() ([]byte, []int) {
	return file_user_event_service_proto_rawDescGZIP(), []int{0}
}

type UserEventsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Event *Event `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
}

func (x *UserEventsResponse) Reset() {
	*x = UserEventsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_event_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserEventsResponse) ProtoMessage() {}

func (x *UserEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_event_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserEventsResponse.ProtoReflect.Descriptor instead.
func (*UserEventsResponse) Descriptor() ([]byte, []int) {
	return file_user_event_service_proto_rawDescGZIP(), []int{1}
}

func (x *UserEventsResponse) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

var File_user_event_service_proto protoreflect.FileDescriptor

var file_user_event_service_proto_rawDesc = []byte{
	0x0a, 0x18, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x0b,
	0x65, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x13, 0x0a, 0x11, 0x55,
	0x73, 0x65, 0x72, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x35, 0x0a, 0x12, 0x55, 0x73, 0x65, 0x72, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x70, 0x62, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x52, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x32, 0x4f, 0x0a, 0x09, 0x55, 0x73, 0x65, 0x72, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x12, 0x42, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x70,
	0x62, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01, 0x42, 0x2d, 0x5a, 0x2b, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x61, 0x6e, 0x75, 0x6d, 0x75, 0x72, 0x61, 0x2f,
	0x67, 0x6f, 0x2d, 0x61, 0x75, 0x74, 0x68, 0x2d, 0x72, 0x62, 0x61, 0x63, 0x2d, 0x73, 0x74, 0x61,
	0x72, 0x74, 0x65, 0x72, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_user_event_service_proto_rawDescOnce sync.Once
	file_user_event_service_proto_rawDescData = file_user_event_service_proto_rawDesc
)

func file_user_event_service_proto_rawDescGZIP() []byte {
	file_user_event_service_proto_rawDescOnce.Do(func() {
		file_user_event_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_user_event_service_proto_rawDescData)
	})
	return file_user_event_service_proto_rawDescData
}

var file_user_event_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_user_event_service_proto_goTypes = []interface{}{
	(*UserEventsRequest)(nil),  // 0: pb.UserEventsRequest
	(*UserEventsResponse)(nil), // 1: pb.UserEventsResponse
	(*Event)(nil),              // 2: pb.Event
}
var file_user_event_service_proto_depIdxs = []int32{
	2, // 0: pb.UserEventsResponse.event:type_name -> pb.Event
	0, // 1: pb.UserEvent.GetUserEvents:input_type -> pb.UserEventsRequest
	1, // 2: pb.UserEvent.GetUserEvents:output_type -> pb.UserEventsResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_user_event_service_proto_init() }
func file_user_event_service_proto_init() {
	if File_user_event_service_proto != nil {
		return
	}
	file_event_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_user_event_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserEventsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_event_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserEventsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_user_event_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_event_service_proto_goTypes,
		DependencyIndexes: file_user_event_service_proto_depIdxs,
		MessageInfos:      file_user_event_service_proto_msgTypes,
	}.Build()
	File_user_event_service_proto = out.File
	file_user_event_service_proto_rawDesc = nil
	file_user_event_service_proto_goTypes = nil
	file_user_event_service_proto_depIdxs = nil
}
